import {Table} from "../../../pages/components/table.ts";
import {DateHelper} from "../../../data-utils/DateHelper.ts";

export const  contestedFormAAmendApplicationDetailsTable: Table = {
    tableName: 'Check your answers',
    rows: [
        { cellItem: 'Is the Applicant represented ?', value: 'Yes', rowType: 'label-value-adjacent' },
        "Solicitor Details",
        { cellItem: 'Solicitor’s name', value: 'Bilbo Baggins' },
        { cellItem: "Solicitor’s firm", value: "FinRem-1-Org" },
        { cellItem: "Your reference number", value: "Y707HZM" },
        "Solicitor’s Contact Details",
        { cellItem: "Is the respondent represented ?", value: "Yes", rowType: 'label-value-adjacent' },
        { cellItem: 'Building and Street', value: '3rd Floor, 65-68 Leadenhall St'},
        { cellItem: 'Town or City', value: 'London'},
        { cellItem: 'County', value: 'Greater London'},
        { cellItem: 'Postcode/Zipcode', value: 'EC3A 2AD'},
        { cellItem: 'Phone Number', value: '07777777777'},
        { cellItem: 'Email', value: 'fr_applicant_solicitor1@mailinator.com'},
        { cellItem: 'Do you consent to receive emails from the court about your case ?', value: 'Yes'},
        { cellItem: 'What type of application is this?', value: 'In connection to matrimonial and civil partnership proceedings (divorce/dissolution etc)', rowType: 'label-value-adjacent' },
        'Divorce / Dissolution Details',
        { cellItem: 'Divorce / Dissolution Case Number', value: 'LV12D12345'},
        { cellItem: 'Does this FR case relate to a Dissolution of a Civil Partnership?', value: 'No'},
        { cellItem: 'Date of marriage / civil partnership', value: '1 Jan 1999'},
        { cellItem: 'Date of separation', value: '1 Jan 2022'},
        { cellItem: 'Application Issued Date', value: DateHelper.getTodayFormattedDate()},
        { cellItem: 'Name of Court / Divorce Centre where petition issued', value: 'Shire Court'},
        { cellItem: 'What stage has the divorce / dissolution case reached ?', value: 'Petition / Application Issued'},
        { cellItem: 'Upload Petition', value: ' PETITION FORM A.docx'},
        'Applicant’s Details',
        { cellItem: 'Current First and Middle names', value: 'Frodo'},
        { cellItem: 'Current Last Name', value: 'Baggins'},
        'Applicant’s Contact details',
        { cellItem: 'Does the applicant live outside of the UK?', value: 'No'},
        { cellItem: 'Building and Street', value: 'Water Unite, 65-68'},
        { cellItem: 'Address Line 2', value: 'Leadenhall Street'},
        { cellItem: 'Town or City', value: 'London'},
        { cellItem: 'Postcode/Zipcode', value: 'EC3A 2AD'},
        { cellItem: 'Country', value: 'United Kingdom'},
        { cellItem: `Keep the Applicant's contact details private from the Respondent?`, value: 'Yes'},
        { cellItem: 'Is the Applicant currently a resident in a refuge?', value: 'Yes'},
        'Respondent’s Details',
        { cellItem: 'Current First and Middle names', value: 'Smeagol'},
        { cellItem: 'Current Last Name', value: 'Gollum'},
        { cellItem: 'Is the respondent represented ?', value: 'Yes', rowType: 'label-value-adjacent'},
        'Respondent’s Solicitor’s Details',
        { cellItem: 'Solicitor’s name', value: 'Sauron'},
        { cellItem: 'Solicitor’s firm', value: 'Mnt Doom Sols'},
        'Respondent’s Solicitor’s Contact Details',
        { cellItem: 'Building and Street', value: 'Coral, 65-68'},
        { cellItem: 'Address Line 2', value: 'Leadenhall Street'},
        { cellItem: 'Town or City', value: 'London'},
        { cellItem: 'Postcode/Zipcode', value: 'EC3A 2AD'},
        { cellItem: 'Country', value: 'United Kingdom'},
        { cellItem: 'Phone Number', value: '07821 639001'},
        { cellItem: 'Email', value: 'fr_respondent_solicitor1@mailinator.com'},
        { cellItem: 'What is the nature of the application ?', value: 'Maintenance Pending SuitLump Sum OrderProperty Adjustment OrderA settlement or a transfer of property for the benefit of the child(ren)Periodical Payment OrderPension Sharing OrderPension Compensation Sharing OrderPension Attachment OrderPension Compensation Attachment OrderVariation Order', rowType: "label-value-adjacent"},
        "Property adjustment order details",
        {cellItem: 'Property address', value: 'Test Address'},
        {cellItem: 'Name(s) and address(es) of any mortgage(s) for property', value: 'Test Mortgage'},
        { cellItem: 'Do you want to add additional property ?', value: 'Yes', rowType: 'label-value-adjacent' },
        { cellItem: 'Property address', value: 'Test Address 2'},
        { cellItem: 'Name(s) and address(es) of any mortgage(s) for property', value: 'Test Mortgage 2'},
        { cellItem: 'Does the application contain any periodical payments or secured periodical payments for children ?', value: 'Yes', rowType: 'label-value-adjacent' },
        { cellItem: 'Has a written agreement been made about maintenance for the benefit of children?', value: 'No', rowType: 'label-value-adjacent' },
        { cellItem: 'What payments are you applying for ?', value: 'For a stepchild or step childrenIn addition to child support or maintenance already paid under a Child Support Agency assessmentTo meet expenses arising from a child’s disabilityTo meet expenses incurred by a child in relation to being educated or training for workWhen either the child or the person with care of the child or the absent parent of the child is not habitually resident in the United Kingdom', rowType: "label-value-adjacent"},
        { cellItem: 'Is the application suitable to be dealt with under the Fast Track Procedure?', value: 'No', rowType: 'label-value-adjacent' },
        'Should this application be allocated to the Complexity List of the Financial Remedies Court?',
        { cellItem: 'A complex case could be retained for hearing within the Financial Remedy Centre and/or allocated to a higher tier of Judiciary', value: 'No'},
        'Please state the current estimated net assets in this case:',
        { cellItem: 'Select one', value: 'Under £250,000 (this should be total of combined net assets, but excluding pensions)'},
        { cellItem: 'Of the above value, what is the net value of the family home?', value: '125000', rowType: 'label-value-adjacent' },
        'Please tick any potential allegations/issues which may arise',
        { cellItem: 'Select all that apply', value: 'Pre- or post-nuptial agreementsComplex asset or income structuresNon-disclosure of assets'},
        { cellItem: 'Please give brief details of the potential allegation/issue:', value: 'Stealing ring', rowType: 'label-value-adjacent' },
        { cellItem: 'Is there any other reason why the case should be allocated to the Complexity List?', value: 'No', rowType: 'label-value-adjacent' },
        { cellItem: 'Do you consider that the case should be allocated to be heard at High Court Judge level?', value: 'No'},
        { cellItem: 'Does anyone in this application need assistance or special facilities when attending court?',  value: 'N/A', rowType: 'label-value-adjacent' },
        { cellItem: 'Does anyone in this application need specific arrangements when attending court?', value: 'N/A', rowType: 'label-value-adjacent' },
        { cellItem: 'Are there any reasons why the case should not proceed in the applicant’s Local Court? If yes, please set out what they are.', value: 'No'},
        { cellItem: 'Has the applicant attended a Mediation information & Assessment Meeting (MIAM)?', value: 'Yes', rowType: 'label-value-adjacent' },
        'Enter details of MIAM certification',
        { cellItem: 'Mediator Registration Number (URN)', value: 'MIAM12345'},
        { cellItem: 'Family Mediation Service Name', value: 'Gandalf the Great Div'},
        { cellItem: 'Sole Trader Name', value: 'Wizard Divorce'},
        'You should have a document signed by the mediator confirming this. Please upload the document here in readiness for the hearing or bring a copy to your first hearing.',
        { cellItem: 'Upload MIAM Document', value: ' test.pdf'},
        'Upload original order to be varied',
        { cellItem: 'Original order to be varied', value: ' Variation order.pdf'},
        { cellItem: 'Do you want to upload any other documents ?', value: 'Yes', rowType: 'label-value-adjacent' },
        'Upload other documents',
        { cellItem: 'Please upload any additional documents related to your application', value: ' NoticeOfActing.pdf'},
        { cellItem: 'Document type', value: 'Notice of acting'},
        'Urgent Case',
        { cellItem: 'Is this an urgent case ?', value: 'Yes'},
        { cellItem: 'Provide details as to why the case is urgent', value: 'Urgent case details'}
 ]
}
