dependencies:
  - name: nodejs
    version: ~1.10.0
    repository: '@hmctspublic'
  - name: ccd
    version: ~4.3.3
    repository: '@hmctspublic'
    tags:
      - fr-ccd-stack
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: 2.2.6
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: elasticsearch
    version: 7.8.1
    repository: '@hmctspublic'
    condition: elastic.enabled
  - name: logstash
    version: 2.4.1
    repository: '@hmctspublic'
    condition: elastic.enabled
