dependencies:
  - name: nodejs
    version: ~1.10.0
    repository: '@hmctspublic'
  - name: ccd
    version: ~3.3.5
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.1.3
    repository: '@hmctspublic'
    tags:
      - idam-pr