dependencies:
  - name: nodejs
    version: ~1.10.0
    repository: '@hmctspublic'
  - name: ccd
    version: ~4.3.3
    repository: '@hmctspublic'
    tags:
      - ccd-pr
  - name: aac-manage-case-assignment
    version: ~0.1.0
    repository: '@hmctspublic'
    condition: aac-manage-case-assignment.enabled
