dependencies:
  - name: nodejs
    version: ~1.10.0
    repository: '@hmctspublic'
  - name: ccd
    version: ~4.3.3
    repository: '@hmctspublic'
    tags:
      - ccd-pr
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: 2.2.6
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: aac-manage-case-assignment
    version: 0.0.11
    repository: '@hmctspublic'
    condition: aac-api.enabled